[[collection]]
type = "card"
title = "chip-8 emulator"
link = "https://github.com/floeckdev/chip-8"
content = "A simple emulator for the CHIP-8 architecture. It is written in Odin, uses MacOS Cocoa for the UI."
tags = ["odin", "cocoa", "emulation"]

[[collection]]
type = "card"
title = "open-sesame"
link = "https://github.com/floeckdev/open-sesame"
content = "Simple program that adds basic security to SSH ports on linux systems."
tags = ["odin", "networking", "ssh", "security"]

[[collection]]
type = "card"
title = "pathfinder"
link = "https://github.com/floeckdev/pathfinder"
content = "A C++ application for solving and generating mazes. Users can solve mazes interactively or choose from various algorithmic solutions, including A* and DFS. Designed to showcase algorithm implementation, user interaction, and performance optimization in C++. "
tags = ["c++", "algorithms", "data structures", "optimisation"]